apiVersion: v1
kind: ConfigMap
metadata:
  name: excoredns
  namespace: kube-system
data:
  Corefile: |-
    .:53 {
        errors
        log
        ready
        k8s_gateway
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
