apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/ori-edge/k8s_gateway/v0.3.4/examples/install-clusterwide.yml
patches:
  - path: patches/configmap_excoredns.yaml
  - path: patches/service_external-dns.yaml