apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - resources/namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.4/manifests/install.yaml
patches:
  - path: patches/secret_argocd-secret.yaml
  - path: patches/configmap_argocd-cm.yaml
  - path: patches/service_argocd-server.yaml
