apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apache
resources:
  - deployment.yaml
  - service.yaml
  - pv.yaml
configMapGenerator:
  - name: main-py
    files:
      - main.py
generatorOptions:
  disableNameSuffixHash: true
