apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app.kubernetes.io/name: api-server
spec:
  selector:
    app.kubernetes.io/name: api-server
  ports:
    - name: http
      port: 80
      protocol: TCP
