apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "meta-monitoring"
  namespace: argocd
  labels:
    app: meta-monitoring
spec:
  destination:
    namespace: meta-monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 51.3.0
    helm:
      releaseName: meta-monitoring
      values: |
        defaultRules:
          create: false
        alertmanager:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: "nginx"
            hosts:
              - "alertmanager.meta.monitoring.homecluster.com"
          ingressPerReplica:
            enabled: true
            ingressClassName: "nginx"
            hostPrefix: "alertmanager"
            hostDomain: "meta.monitoring.homecluster.com"
            paths:
              - "/"
            pathType: "ImplementationSpecific"
          service:
            type: LoadBalancer
            loadBalancerIP: "11.0.1.216"
          servicePerReplica:
            enabled: true
          alertmanagerSpec:
            externalUrl: "http://alertmanager-0.meta.monitoring.homecluster.com"
            replicas: 2
        grafana:
          enabled: true
          service:
            type: LoadBalancer
            loadBalancerIP: "11.0.1.217"
          ingress:
            enabled: true
            ingressClassName: "nginx"
            hosts:
              - "grafana.meta.monitoring.homecluster.com"
          additionalDataSources:
            - name: prometheus-homecluster
              access: proxy  # 'proxy' or 'direct'
              basicAuth: false
              editable: false
              jsonData:
                tlsSkipVerify: true
              type: prometheus
              version: 1
              url: "http://prometheus.k8s.monitoring.homecluster.com"
        kubeApiServer:
          enabled: false
        kubelet:
          enabled: false
        kubeControllerManager:
          enabled: false
        coreDns:
          enabled: false
        kubeDns:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
        prometheusOperator:
          enabled: false
        prometheus:
          ingress:
            enabled: true
            ingressClassName: "nginx"
            hosts:
              - "prometheus.meta.monitoring.homecluster.com"
          ingressPerReplica:
            enabled: true
            ingressClassName: "nginx"
            hostPrefix: "prometheus"
            hostDomain: "meta.monitoring.homecluster.com"
            paths:
              - "/"
            pathType: "ImplementationSpecific"
          service:
            type: LoadBalancer
            loadBalancerIP: "11.0.1.215"
          servicePerReplica:
            enabled: true
          prometheusSpec:
            externalLabels:
              cluster: homecluster
            additionalScrapeConfigs:
              - job_name: "prometheus"
                static_configs:
                - targets:
                  - "prometheus-0.k8s.monitoring.homecluster.com"
                  - "prometheus-1.k8s.monitoring.homecluster.com"
                  labels:
                    cluster: homecluster
            replicas: 2
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        k8s-monitoring-target: "false"
