apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
  namespace: argocd
spec:
  destination:
    namespace: apache
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/alstonzero/argocd-playground.git
    targetRevision: HEAD
    path: k8s-manifest/web-server/httpd
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
