apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 11.0.1.51
    path: /nfsroot/web-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
